import { setupAnalysisUI } from './analysis-ui.mjs';
const worker = new Worker('./worker.mjs', { type: 'module' });
const $ = (id) => document.getElementById(id);
const state = { meta: null, result: null, map: 'z', crossX: null, crossY: null, lastFileName: null };
const els = { file:$('fileInput'),ref:$('referenceInput'),drop:$('dropzone'),workspace:$('workspace'),meta:$('datasetMeta'),pitchAlert:$('pitchAlert'),pitchMode:$('pitchMode'),manualWrap:$('manualPitchWrap'),manualPitch:$('manualPitch'),coeffX:$('coeffX'),coeffY:$('coeffY'),sigma:$('sigma'),sigmaOut:$('sigmaOut'),corr:$('corrOrder'),run:$('runBtn'),reset:$('resetBtn'),summary:$('summaryBtn'),csv:$('csvBtn'),busy:$('busy'),toast:$('toast'),metrics:$('metrics'),heatmap:$('heatmap'),overlay:$('overlay'),tooltip:$('tooltip'),mapTitle:$('mapTitle'),mapDescription:$('mapDescription'),mapUnit:$('mapUnit'),legendMin:$('legendMin'),legendMax:$('legendMax'),legendBar:$('legendBar'),coord:$('coordReadout'),section:$('sectionChart'),sectionLabel:$('sectionLabel'),comparison:$('comparison'),refStatus:$('referenceStatus'),tabs:$('mapTabs'),vectorToggle:$('vectorToggle'),edgeStats:$('edgeStats'),zernikeList:$('zernikeList'),zernikeResidual:$('zernikeResidual') };

['dragenter','dragover'].forEach((ev)=>els.drop.addEventListener(ev,(e)=>{e.preventDefault();els.drop.classList.add('drag');}));
['dragleave','drop'].forEach((ev)=>els.drop.addEventListener(ev,(e)=>{e.preventDefault();els.drop.classList.remove('drag');}));
els.drop.addEventListener('drop',(e)=>{const f=e.dataTransfer.files?.[0];if(f)loadMeasurement(f);});
els.file.addEventListener('change',()=>{const f=els.file.files?.[0];if(f)loadMeasurement(f);});
els.ref.addEventListener('change',async()=>{const f=els.ref.files?.[0];if(!f)return;setBusy(true);worker.postMessage({type:'load-reference',payload:{name:f.name,text:await f.text()}});});
els.pitchMode.addEventListener('change',()=>{els.manualWrap.classList.toggle('hidden',els.pitchMode.value!=='manual');runAnalysis();});
[els.manualPitch,els.coeffX,els.coeffY,els.corr].forEach((el)=>el.addEventListener('change',runAnalysis));
els.sigma.addEventListener('input',()=>{els.sigmaOut.value=els.sigma.value;});els.sigma.addEventListener('change',runAnalysis);
els.run.addEventListener('click',runAnalysis);els.reset.addEventListener('click',()=>location.reload());
els.summary.addEventListener('click',()=>worker.postMessage({type:'export-summary'}));els.csv.addEventListener('click',()=>{setBusy(true);worker.postMessage({type:'export-csv'});});
els.tabs.addEventListener('click',(e)=>{const btn=e.target.closest('button[data-map]');if(!btn)return;state.map=btn.dataset.map;[...els.tabs.querySelectorAll('button')].forEach((b)=>{const on=b===btn;b.classList.toggle('active',on);b.setAttribute('aria-selected',String(on));});renderMap();renderSection();});
els.vectorToggle.addEventListener('change',drawOverlay);
els.overlay.addEventListener('mousemove',mapPointer);els.overlay.addEventListener('click',mapClick);els.overlay.addEventListener('mouseleave',()=>els.tooltip.classList.add('hidden'));
els.overlay.addEventListener('keydown',(e)=>{if(!state.result||state.crossX==null)return;const d={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]}[e.key];if(!d)return;e.preventDefault();state.crossX=Math.max(0,Math.min(state.meta.width-1,state.crossX+d[0]));state.crossY=Math.max(0,Math.min(state.meta.height-1,state.crossY+d[1]));drawOverlay();renderSection();});
window.addEventListener('resize',()=>{if(state.result){renderMap();renderSection();}});

worker.onmessage=({data})=>{
  if(data.type==='overlay-result'){enhancements.overlayResult(data.payload);return;}
  if(data.type==='loaded'){state.meta=data.payload;state.result=null;els.ref.value='';els.refStatus.textContent='기준 파일 없음';els.workspace.classList.remove('hidden');renderMeta();state.crossX=Math.floor(state.meta.width/2);state.crossY=Math.floor(state.meta.height/2);runAnalysis();}
  else if(data.type==='reference-loaded'){els.refStatus.textContent=`Reference: ${data.payload.sourceName}`;toast('Reference loaded locally');runAnalysis();}
  else if(data.type==='reference-cleared'){els.refStatus.textContent='No reference loaded';runAnalysis();}
  else if(data.type==='analysis'){state.result=data.payload;setBusy(false);renderAll();}
  else if(data.type==='summary')downloadText(`${baseName(state.lastFileName)}_summary.json`,JSON.stringify(data.payload,null,2),'application/json');
  else if(data.type==='csv'){setBusy(false);downloadText(data.payload.name,data.payload.csv,'text/csv');}
  else if(data.type==='error'){setBusy(false);toast(data.payload.message,true);if(data.operation==='overlay-csv')enhancements.overlayError(data.payload.message);}
};

async function loadMeasurement(file){if(!file.name.toLowerCase().endsWith('.xyz'))return toast('Please choose a .xyz file.',true);setBusy(true);state.lastFileName=file.name;worker.postMessage({type:'load',payload:{name:file.name,text:await file.text()}});}
function settings(){return{manualPitchMm:els.pitchMode.value==='manual'?Number(els.manualPitch.value):null,coeffX:Number(els.coeffX.value),coeffY:Number(els.coeffY.value),sigmaPx:Number(els.sigma.value),correctionOrder:Number(els.corr.value)};}
function runAnalysis(){if(!state.meta)return;setBusy(true);worker.postMessage({type:'analyze',payload:settings()});}
function setBusy(on){els.busy.classList.toggle('hidden',!on);}function baseName(name){return String(name||'measurement').replace(/\.xyz$/i,'').replace(/[^\w.-]+/g,'_');}
function downloadText(name,text,type){const blob=new Blob([text],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function toast(msg,error=false){els.toast.textContent=msg;els.toast.style.borderColor=error?'#6b2b36':'#35465f';els.toast.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>els.toast.classList.add('hidden'),3600);}

function renderMeta(){const m=state.meta,p=m.defaultPitch,rows=[['File',m.sourceName],['Grid',`${m.width} × ${m.height}`],['Valid',m.validCount.toLocaleString()],['Origin',`${m.phaseOriginX}, ${m.phaseOriginY}`],['CameraRes',m.pitchMmHeader?`${(m.pitchMmHeader*1000).toFixed(2)} µm/px`:'not present'],['Grid span',`${p.spanX.toFixed(2)} × ${p.spanY.toFixed(2)} mm`],['Z range',`${m.minZ.toFixed(4)} … ${m.maxZ.toFixed(4)} µm`],['λ',m.wavelengthNm?`${m.wavelengthNm.toFixed(1)} nm`:'—']];els.meta.innerHTML=rows.map(([k,v])=>`<dt>${escapeHtml(k)}</dt><dd>${escapeHtml(v)}</dd>`).join('');if(m.pitchMmHeader)els.manualPitch.value=m.pitchMmHeader.toFixed(8);}
function renderAll(){renderPitch();renderMetrics();renderMap();renderSection();renderComparison();renderDiagnostics();}
function renderPitch(){const p=state.result.pitch;if(!p.warning){els.pitchAlert.classList.add('hidden');return;}els.pitchAlert.textContent=p.warning;els.pitchAlert.className=`alert ${p.status}`;}
function renderMetrics(){const r=state.result,edge=r.bands.at(-1),items=[['Pitch',`${(r.pitch.pitchMm*1000).toFixed(2)} µm/px`,r.pitch.source],['IPD RMS',fmt(r.before.rms),'gradient proxy'],['Edge RMS',fmt(edge.rms),'85–100% radius'],['Residual RMS',fmt(r.after.rms),`order ${els.corr.value} fit`],['RMS reduction',`${r.reductionPct.toFixed(1)}%`,`${r.fitSamples.toLocaleString()} samples`]];els.metrics.innerHTML=items.map(([l,v,d])=>`<div class="metric"><div class="label">${l}</div><div class="value">${v}</div><div class="detail">${d}</div></div>`).join('');}

const MAPS={z:{title:'Z surface',description:'기준 형상 사용 시 Z − Zref',unit:'µm',signed:false},ipdX:{title:'IPD X',description:'수평 형상 기울기 기반 변위 proxy',unit:'C×µm/mm',signed:true},ipdY:{title:'IPD Y',description:'수직 형상 기울기 기반 변위 proxy',unit:'C×µm/mm',signed:true},magnitude:{title:'IPD magnitude',description:'X/Y 벡터 크기',unit:'C×µm/mm',signed:false},radial:{title:'Radial IPD',description:'웨이퍼 중심에서 바깥 방향 성분',unit:'C×µm/mm',signed:true},tangential:{title:'Tangential IPD',description:'화면 시계 방향이 양수 (+Y 아래)',unit:'C×µm/mm',signed:true},residualMagnitude:{title:'Residual magnitude',description:'선택한 polynomial 보정 후 남은 벡터',unit:'C×µm/mm',signed:false}};
function renderMap(){if(!state.result)return;const key=state.map,cfg=MAPS[key],data=state.result.arrays[key],range=enhancements.range(key,state.result.ranges[key]);els.mapTitle.textContent=cfg.title;els.mapDescription.textContent=cfg.description;els.mapUnit.textContent=enhancements.unit(key);els.legendMin.textContent=fmt(range.min);els.legendMax.textContent=fmt(range.max);els.legendBar.style.background=cfg.signed?'linear-gradient(90deg,#173f79,#52a8cf,#e5ecec,#df8873,#8e294f)':'linear-gradient(90deg,#102345,#176a93,#48b8b0,#e1d36a,#b4374d)';els.legendBar.style.background='linear-gradient(90deg,'+Array.from({length:101},(_,i)=>'rgb('+(cfg.signed?diverging(i/100):thermal(i/100)).join(',')+') '+i+'%').join(',')+')';drawHeatmap(els.heatmap,data,state.meta.width,state.meta.height,range,cfg.signed);drawOverlay();enhancements.render();}
function resizeCanvas(canvas){const rect=canvas.getBoundingClientRect(),dpr=Math.min(2,window.devicePixelRatio||1),w=Math.max(1,Math.round(rect.width*dpr)),h=Math.max(1,Math.round(rect.height*dpr));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;}return{w,h,dpr};}
function waferRect(w,h){const p=state.result?.pitch?.pitchMm||1,d=Math.min(w,h),dw=d*state.meta.width*p/300,dh=d*state.meta.height*p/300;return{x:(w-dw)/2,y:(h-dh)/2,width:dw,height:dh};}
function drawHeatmap(canvas,data,width,height,range,signed){const{w,h}=resizeCanvas(canvas),ctx=canvas.getContext('2d'),off=document.createElement('canvas');off.width=width;off.height=height;const octx=off.getContext('2d'),img=octx.createImageData(width,height),span=range.max-range.min||1;for(let i=0;i<data.length;i++){const v=data[i],p=i*4;if(!Number.isFinite(v)){img.data[p+3]=0;continue;}const t=Math.max(0,Math.min(1,(v-range.min)/span)),[r,g,b]=signed?diverging(t):thermal(t);img.data[p]=r;img.data[p+1]=g;img.data[p+2]=b;img.data[p+3]=255;}octx.putImageData(img,0,0);ctx.clearRect(0,0,w,h);ctx.imageSmoothingEnabled=true;const q=waferRect(w,h);ctx.drawImage(off,0,0,width,height,q.x,q.y,q.width,q.height);}
function thermal(t){return interpStops([[0,14,31,64],[.25,28,100,150],[.5,70,178,177],[.72,238,216,92],[1,168,48,67]],t);}function diverging(t){return interpStops([[0,26,62,122],[.45,107,180,213],[.5,232,238,244],[.55,235,164,139],[1,137,29,59]],t);}function interpStops(stops,t){for(let i=1;i<stops.length;i++){if(t<=stops[i][0]){const a=stops[i-1],b=stops[i],u=(t-a[0])/(b[0]-a[0]);return[1,2,3].map((k)=>Math.round(a[k]+u*(b[k]-a[k])));}}return stops.at(-1).slice(1);}
function drawOverlay(){const{w,h}=resizeCanvas(els.overlay),ctx=els.overlay.getContext('2d'),dpr=Math.min(2,window.devicePixelRatio||1),q=waferRect(w,h);ctx.clearRect(0,0,w,h);ctx.strokeStyle='rgba(214,235,247,.55)';ctx.lineWidth=dpr;ctx.beginPath();ctx.arc(w/2,h/2,Math.min(w,h)/2-2*dpr,0,Math.PI*2);ctx.stroke();drawAxes(ctx,w,h,dpr);if(els.vectorToggle.checked&&state.result)drawVectors(ctx,w,h,dpr,q);if(state.crossX==null)return;const x=q.x+(state.crossX+.5)/state.meta.width*q.width,y=q.y+(state.crossY+.5)/state.meta.height*q.height;ctx.strokeStyle='rgba(255,255,255,.78)';ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke();}
function drawAxes(ctx,w,h,dpr){ctx.fillStyle='rgba(220,235,244,.7)';ctx.font=`${9*dpr}px system-ui`;ctx.textAlign='center';for(const mm of[-150,-100,-50,0,50,100,150]){const x=(mm+150)/300*w,y=(mm+150)/300*h;ctx.fillText(String(mm),Math.max(15*dpr,Math.min(w-15*dpr,x)),h-7*dpr);if(mm!==-150&&mm!==150){ctx.textAlign='left';ctx.fillText(String(mm),4*dpr,Math.max(12*dpr,Math.min(h-12*dpr,y)));ctx.textAlign='center';}}}
function drawVectors(ctx,w,h,dpr,q){const residual=state.map==='residualMagnitude',xs=state.result.arrays[residual?'residualX':'ipdX'],ys=state.result.arrays[residual?'residualY':'ipdY'],mags=state.result.arrays[residual?'residualMagnitude':'magnitude'],cols=Number($('vectorDensity').value),stepX=Math.max(1,Math.floor(state.meta.width/cols)),stepY=Math.max(1,Math.floor(state.meta.height/cols)),scale=Math.min(w,h)/(cols*1.7),cap=Math.max(state.result.ranges[residual?'residualMagnitude':'magnitude'].max,1e-12);ctx.strokeStyle='rgba(245,250,255,.72)';ctx.fillStyle='rgba(245,250,255,.8)';ctx.lineWidth=.75*dpr;for(let gy=Math.floor(stepY/2);gy<state.meta.height;gy+=stepY)for(let gx=Math.floor(stepX/2);gx<state.meta.width;gx+=stepX){const i=gy*state.meta.width+gx,m=mags[i];if(!Number.isFinite(m)||m<=0)continue;const x=q.x+(gx+.5)/state.meta.width*q.width,y=q.y+(gy+.5)/state.meta.height*q.height,len=Math.min(1,m/cap)*scale,ux=xs[i]/m,uy=ys[i]/m,ex=x+ux*len,ey=y+uy*len;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(ex,ey);ctx.stroke();ctx.beginPath();ctx.moveTo(ex,ey);ctx.lineTo(ex-ux*4*dpr-uy*2*dpr,ey-uy*4*dpr+ux*2*dpr);ctx.lineTo(ex-ux*4*dpr+uy*2*dpr,ey-uy*4*dpr-ux*2*dpr);ctx.closePath();ctx.fill();if($('vectorNumbers').checked){ctx.font=(9*dpr)+'px system-ui';ctx.textAlign='left';ctx.fillText(m.toPrecision(3),ex+3*dpr,ey-3*dpr);}}}
function pointerCell(e){const r=els.overlay.getBoundingClientRect(),q=waferRect(r.width,r.height),px=e.clientX-r.left,py=e.clientY-r.top,x=Math.floor((px-q.x)/q.width*state.meta.width),y=Math.floor((py-q.y)/q.height*state.meta.height);return{x:Math.max(0,Math.min(state.meta.width-1,x)),y:Math.max(0,Math.min(state.meta.height-1,y)),left:px,top:py};}
function mapPointer(e){if(!state.result)return;const p=pointerCell(e),i=p.y*state.meta.width+p.x,v=state.result.arrays[state.map][i],pitch=state.result.pitch.pitchMm,cx=(state.meta.width-1)/2,cy=(state.meta.height-1)/2,xmm=(p.x-cx)*pitch,ymm=(p.y-cy)*pitch;els.tooltip.innerHTML=`x ${xmm.toFixed(2)} mm<br>y ${ymm.toFixed(2)} mm<br>${MAPS[state.map].title}: ${Number.isFinite(v)?fmt(v):'No Data'}`;els.tooltip.innerHTML+='<br>X '+fmt(state.result.arrays.ipdX[i])+' · Y '+fmt(state.result.arrays.ipdY[i])+'<br>|IPD| '+fmt(state.result.arrays.magnitude[i])+' · 미보정 (nm 아님)';els.tooltip.style.left=`${Math.min(p.left+12,els.overlay.clientWidth-130)}px`;els.tooltip.style.top=`${Math.max(6,p.top-10)}px`;els.tooltip.classList.remove('hidden');els.coord.textContent=`x ${xmm.toFixed(2)} mm · y ${ymm.toFixed(2)} mm`;}
function mapClick(e){const p=pointerCell(e);state.crossX=p.x;state.crossY=p.y;drawOverlay();renderSection();}
function renderSection(){if(!state.result||state.crossX==null)return;const data=state.result.arrays[state.map],w=state.meta.width,h=state.meta.height,pitch=state.result.pitch.pitchMm,row=new Float32Array(w),col=new Float32Array(h);for(let x=0;x<w;x++)row[x]=data[state.crossY*w+x];for(let y=0;y<h;y++)col[y]=data[y*w+state.crossX];drawLines(els.section,row,col);enhancements.point();const cx=(w-1)/2,cy=(h-1)/2;els.sectionLabel.textContent=`x ${((state.crossX-cx)*pitch).toFixed(2)} mm · y ${((state.crossY-cy)*pitch).toFixed(2)} mm`;}
function drawLines(canvas,row,col){const{w,h}=resizeCanvas(canvas),ctx=canvas.getContext('2d');ctx.clearRect(0,0,w,h);const values=[...row,...col].filter(Number.isFinite);if(!values.length)return;let min=Math.min(...values),max=Math.max(...values);if(min===max){min-=1;max+=1;}ctx.strokeStyle='#243143';ctx.lineWidth=1;for(let k=1;k<5;k++){const y=h*k/5;ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke();}drawSeries(row,'#69a7ff');drawSeries(col,'#42d392');ctx.fillStyle='#9aa6b8';ctx.font=`${11*(window.devicePixelRatio||1)}px system-ui`;ctx.fillText('X section',10,18);ctx.fillStyle='#69a7ff';ctx.fillRect(78,11,18,3);ctx.fillStyle='#9aa6b8';ctx.fillText('Y section',110,18);ctx.fillStyle='#42d392';ctx.fillRect(178,11,18,3);function drawSeries(a,color){ctx.strokeStyle=color;ctx.lineWidth=1.6*(window.devicePixelRatio||1);ctx.beginPath();let started=false;for(let i=0;i<a.length;i++){const v=a[i];if(!Number.isFinite(v)){started=false;continue;}const x=i/(a.length-1)*w,y=h-(v-min)/(max-min)*(h-24)-6;if(!started){ctx.moveTo(x,y);started=true;}else ctx.lineTo(x,y);}ctx.stroke();}}
function renderComparison(){const b=state.result.before,a=state.result.after,max=Math.max(b.max,a.max)||1,rows=[['RMS',b.rms,a.rms],['P95',b.p95,a.p95],['Max',b.max,a.max]];els.comparison.innerHTML=rows.map(([n,bv,av])=>`<div><div class="comp-row"><strong>${n}</strong><span>${fmt(bv)}</span><span>${fmt(av)}</span></div><div class="comp-row"><span>Before</span><div class="bar"><div class="fill" style="width:${Math.min(100,bv/max*100)}%"></div></div><span></span></div><div class="comp-row after"><span>After</span><div class="bar"><div class="fill" style="width:${Math.min(100,av/max*100)}%"></div></div><span></span></div></div>`).join('');}
function renderDiagnostics(){const r=state.result;els.edgeStats.innerHTML=r.bands.map((b)=>`<div class="edge-card"><b>${b.label}</b><strong>${fmt(b.rms)}</strong><span>RMS · max ${fmt(b.max)} · n ${b.count.toLocaleString()}</span></div>`).join('');const modes=r.zernike.modes.filter((m)=>m.name!=='Piston').sort((a,b)=>Math.abs(b.coefficientUm)-Math.abs(a.coefficientUm)).slice(0,8),max=Math.max(...modes.map((m)=>Math.abs(m.coefficientUm)),1e-12);els.zernikeList.innerHTML=modes.map((m)=>`<div class="z-row"><span>${escapeHtml(m.name)}</span><div class="z-bar"><i style="width:${Math.abs(m.coefficientUm)/max*100}%"></i></div><em>${fmt(m.coefficientUm)} µm</em></div>`).join('');els.zernikeResidual.textContent=`fit residual ${fmt(r.zernike.residualRmsUm)} µm`;}
function fmt(v){if(!Number.isFinite(v))return'—';const a=Math.abs(v);if(a>=1000||(a<0.001&&a!==0))return v.toExponential(3);return v.toFixed(a<1?5:a<10?4:3);}function escapeHtml(s){return String(s).replace(/[&<>'"]/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
const enhancements=setupAnalysisUI({state,worker,renderMap,renderSection,fmt,toast});
